name: macro_financial_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scipy
  - statsmodels
  - jupyterlab
  - pyarrow
  - fastparquet
  - requests
  - tqdm
  - python-dotenv
  - pip:
    - yfinance
    - alpha_vantage
    - nasdaq-data-link
    - fredapi
    - pandas-datareader
